name: google-meridian
desc: google-meridian
cmd: |
  git clone https://github.com/medianation/google_meridian.git /tmp/repo && 
  pip install google-meridian[colab,and-cuda] boto3 &&
  python3 /tmp/repo/model_training.py --path="1747297675.641256_geo_all_channels (1).csv"
env:
  image: nvidia/cuda:12.2-runtime
cloud-instance-types:
  - g2.1
