version: "3.8"

networks:
  smd:
    driver: bridge

services:
  # Redis для Celery
  redis:
    image: redis
    restart: always
    networks:
      - smd

  smd-meridian-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_app:latest   # Собираем образ и присваиваем ему тег my_app:latest
    env_file:
      - .env
    command: python -m app.main
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./app/assets:/app/app/assets  # Добавляем volume для директории assets
    depends_on:
      - redis
    networks:
      - smd

  # Celery Worker
  celery:
    build:
      dockerfile: Dockerfile
    mem_limit: 6g
    env_file:
      - .env
    command: celery -A app.celery_tasks.celery:celery worker --pool=prefork --autoscale=10,1 --loglevel=info
    restart: always
    depends_on:
      - redis
      - smd-meridian-app
    networks:
      - smd

